title: Yassin Ezaouibi
logo: /assets/profile-image-new.png
description: Full Stack developer with strong skills in java spring (backend) and Angular (frontend).
show_downloads: false
theme: jekyll-theme-minimal
