title: Yassin Ezaouibi
#logo: /assets/profile-image-new.png
logo: assets/ma_photo-linkedin.preview.v4.png
description: Full Stack developer with strong skills in java spring (backend) and Angular (frontend).
show_downloads: false
theme: jekyll-theme-minimal
