title: Yassin Ezaouibi
logo: /assets/profile-gh-pages.png
description: Full Stack developer with strong skills in java spring (backend) and Angular (frontend). Passionate about designing and developing robust web applications, I look to join a dynamic team to use my skills and contribute to promising projects.
show_downloads: true
theme: jekyll-theme-minimal
